### ISSUE TITLE
Incorrect response format

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhirpath-py-server#1]
As you can see the current version of the service always return a response as a string.
As a result it shows as [string in the UI](https://dev.fhirpath-lab.com/FhirPath?parameters=N4IgpgHgDgTmDO8CWB7AdiAXCALjAhgMZgAUA5HoWQJQB0A5kgG5gYA0Ih6OkOWIafAFswIDq0ZpR2AGYALJDCj4ccgLRQAngAISAITAATfNoDKKGTgDu%20ONTG4wMIUjQoANinqbTTljH45HBwoeEwAenD4AEdPNHlFNRgAFlp8AC8AVzgrMAAjZB54WikccISAjiZbJHw89wQsAG0AXQBfIA).

Please check the [output format of other engines](https://dev.fhirpath-lab.com/FhirPath?parameters=N4IgpgHgDgTmDO8CWB7AdiAXCALjAhgMZgAUA5HoWQJQB0A5kgG5gYA0Ih6OkOWIafAFswIDq0ZpR2AGYALJDCj4ccgLRQAngAISAITAATfNoDKKGTgDu%20ONTG4wMIUjQoANinqbTTljH45HBwoeEwAenD4AEdPNHlFNRgAFlp8AC8AVzgrMAAjZB54WikccISAjiZbJHw89wQsAG0AXQBfIA) and update the implemetnation to return an object instead of a plain string.

**Comment by qscgyjqscgyj** [comment]
Todo list:
- [ ] Function `defineVariable` is not implemented in fhirpath-py but can be used in fhirpath-lab
- [ ] Implement `response.parameters.expectedReturnType` parameter as in rest engines 
- [ ] Implement `response.parameters.parseDebugTree` and `response.parameters.parseDebug` parameters as in rest engines
